USE [master]

CREATE DATABASE [BANCO_TESTE]

USE [BANCO_TESTE]

CREATE TABLE [Mangas]
(
    [ID] INT IDENTITY(1,1),
    [Nome] NVARCHAR(32),
    [Capitulo] INT,
    [DataCriacao] DATETIME NOT NULL
)

INSERT INTO [MINHA_PRIMEIRA_TABELA]
VALUES
(
    'Yasmin',
    17,
    '(11) 982716752',
    GETDATE()
)

SELECT *FROM[MINHA_PRIMEIRA_TABELA]

UPDATE [Mangas]
SET [Capitulo] = '24'
WHERE [Nome] = 'I Have To Be a Monster'

SELECT *FROM [MINHA_PRIMEIRA_TABELA] WHERE [Idade] = 18

SELECT *FROM [Mangas]
WHERE [Capitulo] > 100

INSERT INTO [Mangas]
VALUES
(
    'Kill The hero',
     120,
     GETDATE(),
     'n'
)

ALTER TABLE [Mangas] [Finalizado] CHAR (1)

BEGIN TRANSACTION
DELETE [Mangas]
GO
SELECT *FROM [Mangas]
COMMIT TRANSACTION

ALTER TABLE [Mangas]
ALTER COLUMN [Finalizado] CHAR (1) NOT NULL
 
ROLLBACK TRANSACTION

SELECT [Nome], [Capitulo] FROM  [Mangas]

SELECT DISTINCT [Telefone] FROM [MINHA_PRIMEIRA_TABELA]

SELECT COUNT(Capitulo) from [Mangas]

SELECT TOP 10 * FROM [Mangas]

SELECT *FROM [Mangas]
WHERE [ID] IN (1,2,3)

UPDATE [Mangas]
SET [Capitulo] = 120
WHERE [Nome] =  'Kill The Hero'
GO

SELECT *FROM [Mangas]

EXEC sp_columns [Mangas]

ALTER TABLE [MANGAS]
ALTER COLUMN [ID] INT

Create TABLE [RECOMENDADO]
(
    ID int PRIMARY KEY,
    Recomendo varchar(15)
)

ALTER TABLE [MANGAS]
ADD CONSTRAINT FK_ID FOREIGN KEY (ID) REFERENCES [RECOMENDADO] (ID)

INSERT INTO [RECOMENDADO]
VALUES
(
    1,
    'SIM'
)
