CREATE DATABASE [EXERCICIO]

CREATE TABLE [CLIENTE]
(
    ID_CLIENTE INT PRIMARY KEY NOT NULL,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    SEXO VARCHAR(10) NOT NULL,
    ID_MUNICIPIO INT NOT NULL
)

ALTER TABLE [CLIENTE]
ADD CONSTRAINT FK_IDMUN FOREIGN KEY (ID_MUNICIPIO) REFERENCES [MUNICIPIO] (ID_MUNICIPIO)

INSERT INTO [CLIENTE]
VALUES
(
    9,
    'Getulio Vargas',
    'Masculino',
    2
)
CREATE TABLE [LOCACAO]
(
    ID_LOCACAO INT PRIMARY KEY NOT NULL,
    ID_CLIENTE INT NOT NULL,
    [STATUS] VARCHAR(15) NOT NULL,
    VALOR NUMERIC(2) NOT NULL
)

INSERT INTO [LOCACAO]
VALUES
(
    7,
    7,
    'Atrasado',
    15
)

ALTER TABLE [LOCACAO]
ADD CONSTRAINT FK_IDCLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES [CLIENTE] (ID_CLIENTE)

CREATE TABLE [MUNICIPIO]
(
    ID_MUNICIPIO INT PRIMARY KEY NOT NULL,
    NOME_MUNICIPIO VARCHAR(40),
    UF VARCHAR(2)
)

INSERT INTO [MUNICIPIO]
VALUES
(
    7,
    'Lajeado',
    'TO'
)
--Exercicio 1

SELECT C.ID_CLIENTE, C.NOME_CLIENTE, C.SEXO, L.STATUS, L.VALOR
FROM [CLIENTE] C
INNER JOIN [LOCACAO] AS L ON L.ID_CLIENTE = C.ID_CLIENTE
WHERE STATUS !='Regular'

-- Exercicio 2

SELECT C.ID_CLIENTE, C.NOME_CLIENTE, L.STATUS, L.VALOR
FROM [CLIENTE] C
INNER JOIN [LOCACAO] L ON L.ID_CLIENTE = C.ID_CLIENTE
WHERE L.VALOR < 50 AND STATUS != 'Regular'

-- Exercicio 3

SELECT C.ID_CLIENTE, C.NOME_CLIENTE, M.ID_MUNICIPIO, M.UF
FROM [CLIENTE] C
INNER JOIN [MUNICIPIO] M ON M.ID_MUNICIPIO = C.ID_MUNICIPIO
WHERE M.UF = 'MA'

-- Exercicio 4

SELECT C.ID_CLIENTE, C.NOME_CLIENTE, M.ID_MUNICIPIO, M.UF
FROM [CLIENTE] C
INNER JOIN [MUNICIPIO] M ON M.ID_MUNICIPIO = C.ID_MUNICIPIO
WHERE M.UF = 'MG' AND C.SEXO = 'Feminino'

-- Exercicio 5

SELECT M.ID_MUNICIPIO, M.UF, COUNT(C.ID_CLIENTE) TOTAL_CLIENTES_MUNICIPIO
FROM [MUNICIPIO] M
INNER JOIN [CLIENTE] C ON C.ID_MUNICIPIO = M.ID_MUNICIPIO
GROUP BY M.ID_MUNICIPIO, M.UF

SELECT *FROM [CLIENTE]
SELECT *FROM [MUNICIPIO]
SELECT *FROM [LOCACAO]





