CREATE TABLE Alunos
(
    ID_ALUNO INT PRIMARY KEY NOT NULL,
    NOME VARCHAR(40) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO VARCHAR(1) NOT NULL, -- M PARA MASCULINO E F PARA FEMININO
    DATA_CADASTRO DATETIME NOT NULL,
    LOGIN_CADASTRO VARCHAR(15) NOT NULL,

)

CREATE TABLE SITUACAO
(
    ID_SITUACAO INT PRIMARY KEY NOT NULL,
    SITUACAO VARCHAR(25) NOT NULL,
    DATA_CADASTRO DATETIME,
    LOGIN_CADASTRO VARCHAR(15)
)

CREATE TABLE CURSOS
(
    ID_CURSO INT PRIMARY KEY NOT NULL,
    NOME_CURSO VARCHAR(200) NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL,
    LOGIN_CADASTRO VARCHAR(15) NOT NULL
)

CREATE TABLE TURMAS
(
    ID_TURMA INT PRIMARY KEY NOT NULL,
    ID_ALUNO INT NOT NULL,
    ID_CURSO INT NOT NULL,
    VALOR_TURMA NUMERIC (15,2) NOT NULL,
    DESCONTO NUMERIC (3,2) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_TERMINO DATE,
    DATA_CADASTRO DATETIME NOT NULL,
    LOGIN_CADASTRO VARCHAR (15)
)

ALTER TABLE [TURMAS]
DROP COLUMN [DESCONTO]

ALTER TABLE [TURMAS]
ADD CONSTRAINT FK_ALUNOS FOREIGN KEY (ID_ALUNO) REFERENCES [ALUNOS] (ID_ALUNO)

ALTER TABLE [TURMAS]
ADD CONSTRAINT FK_CURSOS FOREIGN KEY (ID_CURSO) REFERENCES [CURSOS] (ID_CURSO)

CREATE TABLE REGISTRO_PRESENCA
(
    ID_TURMA INT NOT NULL,
    ID_ALUNO INT NOT NULL,
    ID_SITUACAO INT NOT NULL,
    DATA_PRESENCA DATE NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    LOGIN_CADASTRO VARCHAR(15)
)

ALTER TABLE [REGISTRO_PRESENCA]
ADD CONSTRAINT FK_ALUNOSRP FOREIGN KEY (ID_ALUNO) REFERENCES [Alunos] (ID_ALUNO)

ALTER TABLE [REGISTRO_PRESENCA]
ADD CONSTRAINT FK_TURMARP FOREIGN KEY (ID_TURMA) REFERENCES [TURMAS] (ID_TURMA)

ALTER TABLE [REGISTRO_PRESENCA]
ADD CONSTRAINT FK_SITUACAORP FOREIGN KEY (ID_SITUACAO) REFERENCES [SITUACAO] (ID_SITUACAO)


CREATE TABLE [TURMAXALUNOS]
(
    ID_ALUNO INT NOT NULL,
    ID_TURMA INT NOT NULL,
    VALOR NUMERIC (13,2) NOT NULL,
    VALOR_DESCONTO NUMERIC (13,2) ,
    DATA_CADASTRO DATETIME NOT NULL,
    LOGIN_CADASTRO VARCHAR (15) NOT NULL
)

ALTER TABLE [TURMAXALUNOS]
ADD CONSTRAINT FK_TURMA FOREIGN KEY (ID_TURMA) REFERENCES [TURMAS] (ID_TURMA)

ALTER TABLE [TURMAXALUNOS]
ADD CONSTRAINT FK_ALUNOS FOREIGN KEY (ID_ALUNO) REFERENCES [ALUNOS] (ID_ALUNO)


/*
DROP TABLE [TURMAS];
DROP TABLE [SITUACAO];
DROP TABLE [REGISTRO_PRESENCA];
DROP TABLE [CURSOS];
DROP TABLE [Alunos]
*/

INSERT INTO [Alunos]
VALUES
(
    2,
    'Mateus Garcia Santos',
    '29/10/2001',
    'M',
    GETDATE(),
    'Mateus'

)

INSERT INTO [CURSOS]
VALUES
(
    2,
    'Ciências da Programação',
    GETDATE(),
    'Mateus'
)

INSERT INTO [SITUACAO]
VALUES
(
    1,
    'Presença Confirmada',
    GETDATE(),
    'Leozin'

)

INSERT INTO [TURMAS]
VALUES
(
    2,
    2,
    '02/09/2004',
    '02/09/2008',
    GETDATE(),
    'Leozin'

)

INSERT INTO [TURMAXALUNOS]
VALUES
(
    1,
    1,
    2500,
    2300,
    GETDATE(),
    'Leozin'
)

INSERT INTO [REGISTRO_PRESENCA]
VALUES
(
    1,
    1,
    1,
    '17/01/2023',
    GETDATE(),
    'Leozin'
)
SELECT *FROM [TURMAS]

SELECT CURSOS.ID_CURSO, CURSOS.NOME_CURSO, COUNT(TURMAS.ID_TURMA) TOTAL_TURMAS 
FROM [TURMAS] INNER JOIN[CURSOS] ON CURSOS.ID_CURSO = TURMAS.ID_CURSO 
GROUP BY CURSOS.ID_CURSO, CURSOS.NOME_CURSO

SELECT CURSOS.ID_CURSO, CURSOS.NOME_CURSO, TURMAS.ID_TURMA
FROM [TURMAS]
INNER JOIN [CURSOS] ON CURSOS.ID_CURSO = TURMAS.ID_CURSO

SELECT *FROM CURSOS
SELECT *FROM TURMAS

SELECT CURSOS.ID_CURSO, CURSOS.NOME_CURSO, COUNT(TURMAS.ID_TURMA) TOTAL_TURMAS
FROM [CURSOS]
INNER JOIN [TURMAS] ON TURMAS.ID_CURSO = CURSOS.ID_CURSO
GROUP BY CURSOS.ID_CURSO, CURSOS.NOME_CURSO
